python eval_rl.py --model-path "model/Qwen2.5-3B-Instruct" --tokenizer-path "model/Qwen2.5-3B-Instruct" --model-size "3b" --model-type "qwen" --benchmark "math" --data-type "test" --output-dir "outputs_2/math/Qwen3B_517" --max_new_tokens 1024 --temperature 0.0 --eval_batch_size 2000 --seed 42 --budget_forcing --budget_forcing_tokens 517
python eval_rl.py --model-path "model/Qwen2.5-3B-Instruct" --tokenizer-path "model/Qwen2.5-3B-Instruct" --model-size "3b" --model-type "qwen" --benchmark "math" --data-type "test" --output-dir "outputs_2/math/Qwen3B_460" --max_new_tokens 1024 --temperature 0.0 --eval_batch_size 2000 --seed 42 --budget_forcing --budget_forcing_tokens 460
python eval_rl.py --model-path "model/Qwen2.5-3B-Instruct" --tokenizer-path "model/Qwen2.5-3B-Instruct" --model-size "3b" --model-type "qwen" --benchmark "math" --data-type "test" --output-dir "outputs_2/math/Qwen3B_402" --max_new_tokens 1024 --temperature 0.0 --eval_batch_size 2000 --seed 42 --budget_forcing --budget_forcing_tokens 402
python eval_rl.py --model-path "model/Qwen2.5-3B-Instruct" --tokenizer-path "model/Qwen2.5-3B-Instruct" --model-size "3b" --model-type "qwen" --benchmark "math" --data-type "test" --output-dir "outputs_2/math/Qwen3B_345" --max_new_tokens 1024 --temperature 0.0 --eval_batch_size 2000 --seed 42 --budget_forcing --budget_forcing_tokens 345
python eval_rl.py --model-path "model/Qwen2.5-3B-Instruct" --tokenizer-path "model/Qwen2.5-3B-Instruct" --model-size "3b" --model-type "qwen" --benchmark "math" --data-type "test" --output-dir "outputs_2/math/Qwen3B_287" --max_new_tokens 1024 --temperature 0.0 --eval_batch_size 2000 --seed 42 --budget_forcing --budget_forcing_tokens 287




python eval_rl.py --model-path "model/Qwen2.5-3B-Instruct" --tokenizer-path "model/Qwen2.5-3B-Instruct" --model-size "3b" --model-type "qwen" --benchmark "gsm8k" --data-type "test" --output-dir "outputs_2/gsm8k/Qwen3B_283" --max_new_tokens 512 --temperature 0.0 --eval_batch_size 2000 --seed 42 --budget_forcing --budget_forcing_tokens 283
python eval_rl.py --model-path "model/Qwen2.5-3B-Instruct" --tokenizer-path "model/Qwen2.5-3B-Instruct" --model-size "3b" --model-type "qwen" --benchmark "gsm8k" --data-type "test" --output-dir "outputs_2/gsm8k/Qwen3B_252" --max_new_tokens 512 --temperature 0.0 --eval_batch_size 2000 --seed 42 --budget_forcing --budget_forcing_tokens 252
python eval_rl.py --model-path "model/Qwen2.5-3B-Instruct" --tokenizer-path "model/Qwen2.5-3B-Instruct" --model-size "3b" --model-type "qwen" --benchmark "gsm8k" --data-type "test" --output-dir "outputs_2/gsm8k/Qwen3B_220" --max_new_tokens 512 --temperature 0.0 --eval_batch_size 2000 --seed 42 --budget_forcing --budget_forcing_tokens 220
python eval_rl.py --model-path "model/Qwen2.5-3B-Instruct" --tokenizer-path "model/Qwen2.5-3B-Instruct" --model-size "3b" --model-type "qwen" --benchmark "gsm8k" --data-type "test" --output-dir "outputs_2/gsm8k/Qwen3B_189" --max_new_tokens 512 --temperature 0.0 --eval_batch_size 2000 --seed 42 --budget_forcing --budget_forcing_tokens 189
python eval_rl.py --model-path "model/Qwen2.5-3B-Instruct" --tokenizer-path "model/Qwen2.5-3B-Instruct" --model-size "3b" --model-type "qwen" --benchmark "gsm8k" --data-type "test" --output-dir "outputs_2/gsm8k/Qwen3B_157" --max_new_tokens 512 --temperature 0.0 --eval_batch_size 2000 --seed 42 --budget_forcing --budget_forcing_tokens 157


python eval_rl.py --model-path "model/Qwen2.5-3B-Instruct" --tokenizer-path "model/Qwen2.5-3B-Instruct" --model-size "3b" --model-type "qwen" --benchmark "amc" --data-type "test" --output-dir "outputs_2/amc/Qwen3B_797" --max_new_tokens 2048 --temperature 0.0 --eval_batch_size 2000 --seed 42 --budget_forcing --budget_forcing_tokens 797
python eval_rl.py --model-path "model/Qwen2.5-3B-Instruct" --tokenizer-path "model/Qwen2.5-3B-Instruct" --model-size "3b" --model-type "qwen" --benchmark "amc" --data-type "test" --output-dir "outputs_2/amc/Qwen3B_709" --max_new_tokens 2048 --temperature 0.0 --eval_batch_size 2000 --seed 42 --budget_forcing --budget_forcing_tokens 709
python eval_rl.py --model-path "model/Qwen2.5-3B-Instruct" --tokenizer-path "model/Qwen2.5-3B-Instruct" --model-size "3b" --model-type "qwen" --benchmark "amc" --data-type "test" --output-dir "outputs_2/amc/Qwen3B_620" --max_new_tokens 2048 --temperature 0.0 --eval_batch_size 2000 --seed 42 --budget_forcing --budget_forcing_tokens 620
python eval_rl.py --model-path "model/Qwen2.5-3B-Instruct" --tokenizer-path "model/Qwen2.5-3B-Instruct" --model-size "3b" --model-type "qwen" --benchmark "amc" --data-type "test" --output-dir "outputs_2/amc/Qwen3B_531" --max_new_tokens 2048 --temperature 0.0 --eval_batch_size 2000 --seed 42 --budget_forcing --budget_forcing_tokens 531
python eval_rl.py --model-path "model/Qwen2.5-3B-Instruct" --tokenizer-path "model/Qwen2.5-3B-Instruct" --model-size "3b" --model-type "qwen" --benchmark "amc" --data-type "test" --output-dir "outputs_2/amc/Qwen3B_443" --max_new_tokens 2048 --temperature 0.0 --eval_batch_size 2000 --seed 42 --budget_forcing --budget_forcing_tokens 443