#!/bin/bash

export VLLM_ATTENTION_BACKEND=XFORMERS
export HYDRA_FULL_ERROR=1
export WANDB_API_KEY=bf9ae74795eb47b66c791ae2a3952ca1eacacf12
export RAY_memory_monitor_refresh_ms=0

BASE_RUN_NAME=${BASE_RUN_NAME:-"trail"}
MODEL_BASE_PATH=Qwen/Qwen2.5-0.5B-Instruct
DATA_DIR=data/math_qwen
LENGTH=1024
N_GPUS=1
TP=1
TOTAL_RUNS=1
MODEL_SIZE="0.5b"
MODEL_TYPE="qwen"
DATA_TYPE="test"
RUN_NAME="TRAIL"
MODEL_DIR=checkpoints/${RUN_NAME}

python3 -m trail.main_trail \
  algorithm.adv_estimator=grpo \
  custom_reward_function.path=verl/verl/utils/reward_score/lingua_avg.py \
  custom_reward_function.name=compute_score_lingua \
  +algorithm.use_replay_buffer=true \
  +algorithm.replay_buffer.capacity=500 \
  +algorithm.replay_buffer.top_percent=0.1 \
  +algorithm.replay_buffer.min_reward=0.93 \
  +algorithm.replay_buffer.fixed_distill_interval=10 \
  +algorithm.replay_buffer.off_policy_weight=0.1 \
  +algorithm.replay_buffer.batch_size=64 \
  +algorithm.replay_buffer.max_is_weight=10.0 \
  +algorithm.replay_buffer.microbatch_size=4 \
  data.train_files=${DATA_DIR}/train.parquet \
  data.val_files=${DATA_DIR}/test.parquet \
  data.train_batch_size=128 \
  data.val_batch_size=128 \
  data.max_prompt_length=2048 \
  data.max_response_length=1024 \
  actor_rollout_ref.model.path=${MODEL_BASE_PATH} \
  actor_rollout_ref.actor.optim.lr=1e-6 \
  actor_rollout_ref.model.use_remove_padding=True \
  actor_rollout_ref.actor.ppo_mini_batch_size=32 \
  actor_rollout_ref.actor.ppo_micro_batch_size=16 \
  actor_rollout_ref.actor.use_kl_loss=True \
  actor_rollout_ref.actor.kl_loss_coef=0.001 \
  actor_rollout_ref.actor.kl_loss_type=low_var_kl \
  actor_rollout_ref.model.enable_gradient_checkpointing=True \
  actor_rollout_ref.model.use_shm=True \
  actor_rollout_ref.model.lora_rank=32 \
  actor_rollout_ref.model.lora_alpha=32 \
  actor_rollout_ref.model.target_modules=all-linear \
  actor_rollout_ref.rollout.load_format="safetensors" \
  actor_rollout_ref.rollout.layered_summon=True \
  actor_rollout_ref.actor.fsdp_config.fsdp_size=-1 \
  actor_rollout_ref.actor.fsdp_config.param_offload=True \
  actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
  actor_rollout_ref.rollout.log_prob_micro_batch_size=64 \
  actor_rollout_ref.rollout.tensor_model_parallel_size=$TP \
  actor_rollout_ref.rollout.name=vllm \
  actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
  actor_rollout_ref.rollout.enable_chunked_prefill=False \
  actor_rollout_ref.rollout.enforce_eager=False \
  actor_rollout_ref.rollout.free_cache_engine=True \
  actor_rollout_ref.rollout.n=8 \
  actor_rollout_ref.rollout.max_num_seqs=512 \
  actor_rollout_ref.rollout.max_model_len=2048 \
  actor_rollout_ref.rollout.max_num_batched_tokens=32768 \
  actor_rollout_ref.ref.log_prob_micro_batch_size=16 \
  reward_model.enable=False \
  algorithm.kl_ctrl.kl_coef=0.001 \
  trainer.critic_warmup=0 \
  trainer.val_before_train=False \
  trainer.default_local_dir=$MODEL_DIR \
  trainer.default_hdfs_dir=null \
  trainer.logger=['console'] \
  trainer.project_name='verl_math' \
  trainer.experiment_name=${RUN_NAME} \
  trainer.n_gpus_per_node=$N_GPUS \
  trainer.nnodes=1 \
  trainer.save_freq=20 \
  trainer.test_freq=1000000 \
  trainer.total_epochs=3