NOW=$(date +%Y%m%d)
MODEL_PATH=Qwen/Qwen2.5-1.5B-Instruct
export WANDB_DIR=trail-lora-qwen2.5-1.5b-${NOW}
export WANDB_PROJECT=${WANDB_DIR}
export WANDB_EXP=1.5b-${NOW}
export VLLM_ATTENTION_BACKEND=XFORMERS
set -x
nnodes=1
ngpu_per_node=1
total_procs=32
mini_batch_size=8



python3 -m trail.main_trail \
    algorithm.adv_estimator=grpo \
    custom_reward_function.path=verl/verl/utils/reward_score/lingua_avg.py \
    custom_reward_function.name=compute_score_lingua \
    data.train_files=data/math_qwen/train.parquet \
    data.val_files=data/math_qwen/test.parquet \
    data.train_batch_size=${total_procs} \
    data.val_batch_size=${total_procs} \
    data.max_prompt_length=512 \
    data.max_response_length=1024 \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    data.shuffle=True \
    actor_rollout_ref.model.path=$MODEL_PATH  \
    actor_rollout_ref.model.use_shm=True  \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.model.lora_rank=32 \
    actor_rollout_ref.model.lora_alpha=32 \
    actor_rollout_ref.model.target_modules=all-linear \
    actor_rollout_ref.actor.optim.lr=3e-5 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=${mini_batch_size} \
    actor_rollout_ref.actor.ppo_micro_batch_size=${mini_batch_size} \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.fsdp_config.fsdp_size=-1 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=${mini_batch_size} \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
    actor_rollout_ref.rollout.n=5 \
    actor_rollout_ref.rollout.max_num_seqs=512 \
    actor_rollout_ref.rollout.max_model_len=1536 \
    actor_rollout_ref.rollout.max_num_batched_tokens=1536 \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.load_format=safetensors \
    actor_rollout_ref.rollout.layered_summon=True \
    actor_rollout_ref.ref.log_prob_micro_batch_size=${mini_batch_size} \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=1 \
    actor_rollout_ref.actor.entropy_coeff=0.001 \
    algorithm.kl_ctrl.kl_coef=0.001 \
    algorithm.use_kl_in_reward=False \
    trainer.val_before_train=False \
    trainer.critic_warmup=0 \
    trainer.logger='["console","swanlab"]' \
    trainer.project_name=${WANDB_PROJECT} \
    trainer.experiment_name=${WANDB_EXP} \
    trainer.n_gpus_per_node=1 \
    trainer.nnodes=1 \
    trainer.save_freq=5 \
    trainer.test_freq=5000000 \
    trainer.total_epochs=3 \
    +trainer.max_ckpt_to_keep=2 \
    +algorithm.use_replay_buffer=true \
    +algorithm.replay_buffer.capacity=500 \
    +algorithm.replay_buffer.top_percent=0.1 \
    +algorithm.replay_buffer.min_reward=0.8 \
    +algorithm.replay_buffer.fixed_distill_interval=5 \
    +algorithm.replay_buffer.off_policy_weight=0.1 \
    +algorithm.replay_buffer.batch_size=16 \
    +algorithm.replay_buffer.max_is_weight=10.0 \
    +algorithm.replay_buffer.microbatch_size=4